/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliotecamagica.Vistas;

import com.mycompany.bibliotecamagica.Arboles.Libro;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Ana
 */
public class AgregarLibro extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibro
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private JTextField tituloField;
    private JTextField isbnField;
    private JTextField generoField;
    private JSpinner anioSpinner;
    private JTextField autorField;
    private JComboBox<String> estadoComboBox;
    private JButton guardarButton;

    public AgregarLibro() {
        // Configuración básica de la ventana
        setTitle("Formulario de Registro de Libro");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(400, 300));
        
        // Usamos GridBagLayout para un formulario bien alineado
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        
        // Insets añaden un pequeño espacio (padding) alrededor de cada componente
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST; // Alinear etiquetas a la izquierda

        // --- Fila 0: Título ---
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(new JLabel("Título:"), gbc);
        
        gbc.gridx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL; // Hacer que el campo de texto se estire
        gbc.weightx = 1.0; // Permitir que la columna 1 crezca en ancho
        tituloField = new JTextField(20);
        panel.add(tituloField, gbc);

        // --- Fila 1: ISBN ---
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.NONE; // Resetear
        gbc.weightx = 0; // Resetear
        panel.add(new JLabel("ISBN:"), gbc);
        
        gbc.gridx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        isbnField = new JTextField(20);
        panel.add(isbnField, gbc);

        // --- Fila 2: Autor ---
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.NONE;
        panel.add(new JLabel("Autor:"), gbc);
        
        gbc.gridx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        autorField = new JTextField(20);
        panel.add(autorField, gbc);

        // --- Fila 3: Género ---
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.NONE;
        panel.add(new JLabel("Género:"), gbc);
        
        gbc.gridx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generoField = new JTextField(20);
        panel.add(generoField, gbc);

        // --- Fila 4: Año ---
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.NONE;
        panel.add(new JLabel("Año:"), gbc);
        
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST; // Alinear el spinner a la izquierda
        gbc.fill = GridBagConstraints.NONE;
        // Modelo: (valor inicial, mínimo, máximo, incremento)
        SpinnerNumberModel anioModel = new SpinnerNumberModel(2024, 1500, 2100, 1);
        anioSpinner = new JSpinner(anioModel);
        // Evita que el editor de texto del spinner sea editable
        JSpinner.NumberEditor editor = (JSpinner.NumberEditor)anioSpinner.getEditor();
        editor.getTextField().setEditable(false);
        panel.add(anioSpinner, gbc);

        // --- Fila 5: Estado ---
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.NONE;
        panel.add(new JLabel("Estado:"), gbc);
        
        gbc.gridx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        // Agregamos una opción "nula" al inicio para poder validar
        String[] estados = {"<Seleccione un estado>", "disponible", "prestado", "en tránsito", "agotado"};
        estadoComboBox = new JComboBox<>(estados);
        panel.add(estadoComboBox, gbc);

        // --- Fila 6: Botón de Guardar ---
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 2; // Que el botón ocupe las dos columnas
        gbc.anchor = GridBagConstraints.CENTER; // Centrar el botón
        gbc.fill = GridBagConstraints.NONE;
        guardarButton = new JButton("Guardar Libro");
        panel.add(guardarButton, gbc);
        
        // *** Lógica de validación en el ActionListener del botón ***
        guardarButton.addActionListener((ActionEvent e) -> {
            validarFormulario();
        });

        // Añadir el panel principal al frame
        add(panel);
        pack(); // Ajustar tamaño de la ventana a los componentes
        setLocationRelativeTo(null); // Centrar en pantalla
    }

    /**
     * Método que contiene la lógica de validación solicitada.
     */
    private void validarFormulario() {
        // 1. Obtener los valores de los campos
        // .trim() elimina espacios en blanco al inicio y al final
        String titulo = tituloField.getText().trim();
        String isbn = isbnField.getText().trim();
        String genero = generoField.getText().trim();
        String autor = autorField.getText().trim();
        
        // Para el JComboBox, revisamos el índice. El índice 0 es "<Seleccione...>"
        int estadoIndex = estadoComboBox.getSelectedIndex();
        
        // El JSpinner (año) siempre tiene un valor, así que no necesita
        // ser validado por "vacío".

        // 2. Verificar que todos los campos estén llenos
        if (titulo.isEmpty() || isbn.isEmpty() || genero.isEmpty() || autor.isEmpty() || estadoIndex == 0) {
            
            // 3. Si falta alguno, lanzar aviso de advertencia
            JOptionPane.showMessageDialog(this, // 'this' es el JFrame
                    "Error: Todos los campos son obligatorios.",
                    "Campos Vacíos",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            // 4. (Opcional) Si todo está bien, mostrar éxito
            String estado = (String) estadoComboBox.getSelectedItem();
            int anio = (Integer) anioSpinner.getValue();
            
            String mensajeExito = "¡Libro guardado con éxito!\n\n" +
                                  "Título: " + titulo + "\n" +
                                  "Autor: " + autor + "\n" +
                                  "Año: " + anio + "\n" +
                                  "Estado: " + estado;
                                  
            JOptionPane.showMessageDialog(this,
                    mensajeExito,
                    "Registro Completo",
                    JOptionPane.INFORMATION_MESSAGE);
            
            
            
            //objeto del libro a crear
            Libro libroCreado = new Libro(titulo, autor, isbn,anio,autor,estado);
            
            System.out.println("Libro a Crear: " + libroCreado);
            
            // Aquí podrías, por ejemplo, limpiar el formulario
            // limpiarFormulario();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
