/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliotecamagica.Vistas;

import com.mycompany.bibliotecamagica.Arboles.Biblioteca;
import com.mycompany.bibliotecamagica.Arboles.Libro;
import com.mycompany.bibliotecamagica.CargaArchivo;
import com.mycompany.bibliotecamagica.CatalogoGlobal;
import com.mycompany.bibliotecamagica.EstructurasBasicas.Grafo;
import com.mycompany.bibliotecamagica.EstructurasBasicas.HashTableISBN;
import com.mycompany.bibliotecamagica.EstructurasBasicas.ListaNoOrdenada;
import com.mycompany.bibliotecamagica.SimuladorCompleto;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class VistaGeneralFrame extends javax.swing.JFrame {

    Map<String, Biblioteca> bibliotecas = new HashMap<>();
    Grafo grafo = new Grafo();
    HashTableISBN hash = new HashTableISBN();
    CargaArchivo cargador = new CargaArchivo();
    CatalogoGlobal catalogoGlobal;
    ListaNoOrdenada listaNoOrdenada;

    /**
     * Creates new form VistaGeneral
     */
    public VistaGeneralFrame() {
        initComponents();
        bibliotecas = new HashMap<>();
        grafo = new Grafo();
        hash = new HashTableISBN();
        cargador = new CargaArchivo();

        catalogoGlobal = new CatalogoGlobal(bibliotecas, hash);
        listaNoOrdenada = new ListaNoOrdenada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BusquedasPanel = new javax.swing.JButton();
        Ordenamiento = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Graficador = new javax.swing.JButton();
        PanelLibros = new javax.swing.JButton();
        biblioteca = new javax.swing.JButton();
        CargaArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(151, 131, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 205, 205));
        jLabel1.setText("BIBLIOTECA MAGICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 340, 50));

        BusquedasPanel.setText("Busquedas");
        BusquedasPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedasPanelActionPerformed(evt);
            }
        });
        jPanel1.add(BusquedasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        Ordenamiento.setText("Ordenamiento");
        Ordenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenamientoActionPerformed(evt);
            }
        });
        jPanel1.add(Ordenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jButton3.setText("Simulacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        Graficador.setText("Graficas");
        Graficador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficadorActionPerformed(evt);
            }
        });
        jPanel1.add(Graficador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        PanelLibros.setText("Libros");
        PanelLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(PanelLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        biblioteca.setText("Biblioteca");
        biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaActionPerformed(evt);
            }
        });
        jPanel1.add(biblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        CargaArchivo.setText("Carga Archivo");
        CargaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargaArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GraficadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficadorActionPerformed
        // TODO add your handling code here:
        PanelGraficador g = new PanelGraficador(bibliotecas, grafo, hash);
        g.setVisible(true);
    }//GEN-LAST:event_GraficadorActionPerformed

    private void bibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaActionPerformed
        // TODO add your handling code here:
        PanelBibliotecas ventana = new PanelBibliotecas(bibliotecas, grafo);
        ventana.setVisible(true);

    }//GEN-LAST:event_bibliotecaActionPerformed

    private void PanelLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelLibrosActionPerformed
        // TODO add your handling code here:
        PanelLibros ventana = new PanelLibros(bibliotecas, hash);
        ventana.setVisible(true);
    }//GEN-LAST:event_PanelLibrosActionPerformed

    private void BusquedasPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedasPanelActionPerformed
        // TODO add your handling code here:
        PanelBusqueda ventana = new PanelBusqueda(catalogoGlobal, listaNoOrdenada);
        ventana.setVisible(true);
    }//GEN-LAST:event_BusquedasPanelActionPerformed

    private void OrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenamientoActionPerformed
        // TODO add your handling code here:
        if (listaNoOrdenada == null || listaNoOrdenada.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay libros cargados todavía.");
            return;
        }
        PanelOrdenamiento ventana = new PanelOrdenamiento(listaNoOrdenada);
        ventana.setVisible(true);
    }//GEN-LAST:event_OrdenamientoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PanelDespacho ventana = new PanelDespacho(grafo, bibliotecas);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CargaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaArchivoActionPerformed

        PanelCargaArchivos ventana = new PanelCargaArchivos(bibliotecas, grafo, hash, cargador);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                listaNoOrdenada.limpiar();

                for (Biblioteca b : bibliotecas.values()) {
                    if (b.getArbolAvl() != null) {
                        for (Libro l : b.getArbolAvl().obtenerTodosLosLibros()) {
                            listaNoOrdenada.agregar(l);
                        }
                    }
                    if (b.getArbolB() != null) {
                        for (Libro l : b.getArbolB().obtenerTodosLosLibros()) {
                            listaNoOrdenada.agregar(l);
                        }
                    }
                    if (b.getArbolBMas() != null) {
                        for (Libro l : b.getArbolBMas().obtenerTodosLosLibros()) {
                            listaNoOrdenada.agregar(l);
                        }
                    }
                }

                System.out.println(" Se cargaron " + listaNoOrdenada.getTamaño() + " libros al catálogo global.");
            }
        });

        ventana.setVisible(true);


    }//GEN-LAST:event_CargaArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGeneralFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedasPanel;
    private javax.swing.JButton CargaArchivo;
    private javax.swing.JButton Graficador;
    private javax.swing.JButton Ordenamiento;
    private javax.swing.JButton PanelLibros;
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}